### ISSUE TITLE
favicon 

### ISSUE THREAD

**Issue by Olga-Skoroded** [ssamvelk/toxin#15]
В сафари своя версия favicon, ее тоже обязательно надо настраивать.
То есть нужна svg для контура иконки, и нужен цвет для иконки при наведении. [(статья)](https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/)

**Comment by Olga-Skoroded** [comment]
favicon.ico дублируется в папке static и static/favicon 
![favicon](https://user-images.githubusercontent.com/68814270/96723261-8a5ac400-13d8-11eb-8dd9-5efdc0f7ef01.png)

**Comment by ssamvelk** [comment]
> 
> 
> favicon.ico дублируется в папке static и static/favicon
> ![favicon](https://user-images.githubusercontent.com/68814270/96723261-8a5ac400-13d8-11eb-8dd9-5efdc0f7ef01.png)

поправил
